/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapscloud_libnativemate_basic_NativeMate */

#ifndef _Included_com_mapscloud_libnativemate_basic_NativeMate
#define _Included_com_mapscloud_libnativemate_basic_NativeMate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mapscloud_libnativemate_basic_NativeMate
 * Method:    getNativeMate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mapscloud_libnativemate_basic_NativeMate_getNativeMate__
  (JNIEnv *, jclass);

/*
 * Class:     com_mapscloud_libnativemate_basic_NativeMate
 * Method:    getNativeMate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mapscloud_libnativemate_basic_NativeMate_getNativeMate__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mapscloud_libnativemate_basic_NativeMate
 * Method:    getNativeMate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mapscloud_libnativemate_basic_NativeMate_getNativeMate__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
