/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapscloud_libnativemate_basic_NativePort */

#ifndef _Included_com_mapscloud_libnativemate_basic_NativePort
#define _Included_com_mapscloud_libnativemate_basic_NativePort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mapscloud_libnativemate_basic_NativePort
 * Method:    getNativeMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mapscloud_libnativemate_basic_NativePort_getNativeMethod__
  (JNIEnv *, jclass);

/*
 * Class:     com_mapscloud_libnativemate_basic_NativePort
 * Method:    getNativeMethod
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mapscloud_libnativemate_basic_NativePort_getNativeMethod__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mapscloud_libnativemate_basic_NativePort
 * Method:    getNativeMethod
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mapscloud_libnativemate_basic_NativePort_getNativeMethod__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
